spring:
  profiles:
    active: local
  cloud:
    stream:
      bindings:
        input-insurance-mailing:
          destination: insurance-mailing
          content-type: application/json
          group: insurance-mailing-group
          durableSubscription: true
      default-binder: rabbit